# Stub for the `libfive` module that only exists inside the PythonSCAD application (the
# libfive expression-tree bindings pysolidfive builds its SDFs on). Deliberately permissive.
from typing import Any

def x() -> Any: ...
def y() -> Any: ...
def z() -> Any: ...
def min(*args: Any) -> Any: ...
def max(*args: Any) -> Any: ...
def abs(v: Any) -> Any: ...
def sqrt(v: Any) -> Any: ...
def sin(v: Any) -> Any: ...
def cos(v: Any) -> Any: ...
def atan2(a: Any, b: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
