# Stub for the `openscad` module that only exists inside the PythonSCAD application.
# Deliberately permissive (see pythonscad.pyi).
from typing import Any

class PyOpenSCAD:
    def __getattr__(self, name: str) -> Any: ...
    def __or__(self, other: Any) -> "PyOpenSCAD": ...
    def __and__(self, other: Any) -> "PyOpenSCAD": ...
    def __sub__(self, other: Any) -> "PyOpenSCAD": ...
    def __add__(self, other: Any) -> "PyOpenSCAD": ...

def hull(*args: Any, **kwargs: Any) -> Any: ...
def polygon(*args: Any, **kwargs: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
