# Stub for the `pythonscad` module that only exists inside the PythonSCAD application
# (native bindings). Deliberately permissive -- every callable takes/returns Any -- so
# pyright can check the surrounding project code without inventing false constraints for
# the native API. The explicitly listed names are the ones the toolkit star-imports;
# anything else resolves through the module-level __getattr__.
from typing import Any

def circle(*args: Any, **kwargs: Any) -> Any: ...
def color(*args: Any, **kwargs: Any) -> Any: ...
def cube(*args: Any, **kwargs: Any) -> Any: ...
def cylinder(*args: Any, **kwargs: Any) -> Any: ...
def difference(*args: Any, **kwargs: Any) -> Any: ...
def edge(*args: Any, **kwargs: Any) -> Any: ...
def fill(*args: Any, **kwargs: Any) -> Any: ...
def frep(*args: Any, **kwargs: Any) -> Any: ...
def hull(*args: Any, **kwargs: Any) -> Any: ...
def intersection(*args: Any, **kwargs: Any) -> Any: ...
def linear_extrude(*args: Any, **kwargs: Any) -> Any: ...
def minkowski(*args: Any, **kwargs: Any) -> Any: ...
def mirror(*args: Any, **kwargs: Any) -> Any: ...
def offset(*args: Any, **kwargs: Any) -> Any: ...
def osimport(*args: Any, **kwargs: Any) -> Any: ...
def osuse(*args: Any, **kwargs: Any) -> Any: ...
def polygon(*args: Any, **kwargs: Any) -> Any: ...
def polyhedron(*args: Any, **kwargs: Any) -> Any: ...
def projection(*args: Any, **kwargs: Any) -> Any: ...
def resize(*args: Any, **kwargs: Any) -> Any: ...
def rotate(*args: Any, **kwargs: Any) -> Any: ...
def rotate_extrude(*args: Any, **kwargs: Any) -> Any: ...
def scale(*args: Any, **kwargs: Any) -> Any: ...
def sphere(*args: Any, **kwargs: Any) -> Any: ...
def square(*args: Any, **kwargs: Any) -> Any: ...
def text(*args: Any, **kwargs: Any) -> Any: ...
def textmetrics(*args: Any, **kwargs: Any) -> Any: ...
def translate(*args: Any, **kwargs: Any) -> Any: ...
def union(*args: Any, **kwargs: Any) -> Any: ...
def __getattr__(name: str) -> Any: ...
