# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_tesselations_render.py
#    Renders a representative sample of tesselations.py's 2-D lid patterns (extruded, so the
#    camera has a solid to frame) with the *real* PythonSCAD binary and compares them against
#    committed golden images. The goldens were generated from the original bosl2-region-op
#    implementation, so they double as the regression baseline for the pysolidfive migration.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ and are generated by
#    tests/generate_golden_images.py.
#
# FileGroup: tesselations

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_cap_box import find_bosl2_scad_dir
from render_pysolidfive import compare_images, find_pythonscad_binary
from render_shapes import render_shapes_shape

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

# Fine 2-D detail (thin webs between tiles) -- rendered (and diffed against) at a higher
# resolution, same rationale as test_labels_render.py's IMGSIZE.
IMGSIZE = (640, 480)

SHAPES = [
    # the grid-repeat drivers (and their single-cell placement variants), tiling a simple child
    ("tesselation_hex_repeat", "HexagonTesselationRepeat(3, 3, 15, children=circle(r=6)).linear_extrude(height=2)"),
    (
        "tesselation_hex_at_location",
        "HexagonTesselationRepeatAtLocation(1, 1, 15, children=circle(r=6)).linear_extrude(height=2)",
    ),
    ("tesselation_triangle_repeat", "TriangleTesselationRepeat(3, 3, 15, children=circle(r=5)).linear_extrude(height=2)"),
    (
        "tesselation_triangle_at_location",
        "TriangleTesselationRepeatAtLocation(1, 1, 15, children=circle(r=5)).linear_extrude(height=2)",
    ),
    # hex/square outline distortion (these return region/path DATA -- render via region()/
    # polygon(), the same way their docstrings direct callers to)
    (
        "tesselation_hexagonal_outline",
        "polygon(HexagonalTesselation(points=[[[-0.5, 0], [0, 0.2], [0.5, 0]], [[-0.5, 0], [0, -0.2], [0.5, 0]], "
        "[[-0.5, 0], [0.3, 0.2], [0.5, 0]]], radius=15)).linear_extrude(height=2)",
    ),
    (
        "tesselation_square_outline",
        "region(SquareTesselation(points=[[[-0.5, 0], [0, 0.2], [0.5, 0]], [[-0.5, 0], [0, -0.2], [0.5, 0]]], "
        "size=[20, 20], thickness=1)).linear_extrude(height=2)",
    ),
    ("tesselation_drop", "TesselationDrop(size=[20.0, 20.0], thickness=1).linear_extrude(height=2)"),
    # leaf family: solid, the vein-outline region variants, and the grouped-three layout
    ("tesselation_leaf", "TesselationLeaf(20).linear_extrude(height=2)"),
    ("tesselation_leaf_outline", "region(TesselationLeafOutline(20)).linear_extrude(height=2)"),
    (
        "tesselation_leaf_outline_veins",
        "region(TesselationLeafOutline(20, with_veins=True)).linear_extrude(height=2)",
    ),
    ("tesselation_leaf_outline_three", "TesselationLeafOutlineThree(20).linear_extrude(height=2)"),
    # region-boolean tilings
    ("tesselation_deltoid", "DeltoidTrihexagonalTiling(20).linear_extrude(height=2)"),
    ("tesselation_deltoid_kite", "DeltoidTrihexagonalTiling(20, kite=True).linear_extrude(height=2)"),
    ("tesselation_rhombi", "RhombiTriHexagonal(20).linear_extrude(height=2)"),
    ("tesselation_half_hexagon", "HalfRegularHexagon(20).linear_extrude(height=2)"),
    ("tesselation_pegasus", "TesselationPegasus([20.0, 20.0]).linear_extrude(height=2)"),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_shapes_shape(expr, out_png, imgsize=IMGSIZE)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )


def _make_test(name: str, expr: str):
    def test(self: RealRenderTestCase) -> None:
        self._render_and_compare(name, expr)

    test.__name__ = f"test_{name}"
    return test


# One test method per SHAPES entry, generated dynamically -- same pattern as
# tests/test_shapes_render.py.
for _name, _expr in SHAPES:
    setattr(RealRenderTestCase, f"test_{_name}", _make_test(_name, _expr))


if __name__ == "__main__":
    unittest.main()
