# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_labels_render.py
#    Renders a representative sample of labels.py shapes with the *real* PythonSCAD binary and
#    compares them against committed golden images. Complements tests/test_labels.py
#    (LabelOptions/MakeLabelOptions only). Every one of the shapes below turned up a real bug the
#    first time it was actually rendered (see git history for specifics):
#      - Bosl2Solid (pybosl2/ port, e.g. shapes3d.cuboid()/prismoid()) mixed directly into a native
#        boolean op (`|`/`-`) without unwrapping `.shape` first
#      - shapes3d.prismoid()'s height kwarg is `h`, not `height`
#      - textmetrics() returns a plain dict (keys "size"/"descent"/...), not an object with
#        `.size`/`.descent` attributes
#      - native .rotate(angle) (bare scalar, no axis) isn't supported by this PythonSCAD build --
#        only the vector form .rotate([0,0,angle]) is
#      - native .resize(newsize) requires a 3-element vector even for 2-D text, and doesn't
#        support an `auto=` kwarg at all
#    None of these are catchable by a numeric mock -- they only show up once real geometry is
#    actually meshed and composed.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available: no PythonSCAD binary, or no working BOSL2/std.scad for PythonSCAD
#    (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ (shared with the other render-test modules) and
#    are generated by tests/generate_golden_images.py (run manually on a machine where rendering
#    works; it dispatches to every module's SHAPES list).
#
# FileGroup: labels

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
# mock_libfive.py/render_pysolidfive.py now live inside pysolidfive/tests/ (moved there so
# pysolidfive's own test suite is bundled with the package); add that directory too.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_cap_box import find_bosl2_scad_dir
from render_labels import render_labels_shape
from render_pysolidfive import compare_images, find_pythonscad_binary

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

# Labels are mostly fine surface detail (etched text, thin stripes) rather than gross shape --
# the default 320x240 doesn't leave enough pixels to make the text/stripes out at all (they
# just read as a faint texture), so render (and diff against) these at a higher resolution
# instead, same rationale as test_cap_box_render.py's IMGSIZE.
IMGSIZE = (800, 600)

# (test-name-suffix, labels.py expression) -- one per distinct technique rather than one per
# public function: the 2-D and 3-D striped-grid backgrounds, the two label frame styles
# (solid/striped background) that MakeFramedLidLabel picks between, the combined framed label
# (adds the finger-hole cutouts), and the frameless (text-only) label. Sized larger than a
# real lid label would need (offset/border margins are fixed-mm, not scaled to label size, so a
# bigger label leaves proportionally more room for the text/stripes -- also needed to actually
# see them at all).
SHAPES = [
    ("striped_grid_2d", "MakeStripedGrid([40.0, 100.0]).linear_extrude(height=2)"),
    ("striped_grid_3d", "Make3dStripedGrid([40.0, 100.0], height=1.0)"),
    (
        "label_solid",
        "MakeMainLidLabelSolid([40.0, 160.0], lid_thickness=2.0, label='Australia', options=MakeLabelOptions())",
    ),
    (
        "label_striped",
        "MakeMainLidLabelStriped([40.0, 160.0], lid_thickness=2.0, label='Australia', options=MakeLabelOptions())",
    ),
    (
        "label_framed",
        "MakeFramedLidLabel([200.0, 40.0], lid_thickness=2.0, label='Frog', options=MakeLabelOptions())",
    ),
    (
        "label_frameless",
        "MakeFramelessLidLabel([80.0, 160.0], lid_thickness=2.0, label='Frog', "
        "options=MakeLabelOptions(font='Stencil Std:style=Bold', label_type=LabelType.FRAMELESS))",
    ),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_labels_shape(expr, out_png, imgsize=IMGSIZE)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )

    def test_striped_grid_2d(self) -> None:
        self._render_and_compare(*SHAPES[0])

    def test_striped_grid_3d(self) -> None:
        self._render_and_compare(*SHAPES[1])

    def test_label_solid(self) -> None:
        self._render_and_compare(*SHAPES[2])

    def test_label_striped(self) -> None:
        self._render_and_compare(*SHAPES[3])

    def test_label_framed(self) -> None:
        self._render_and_compare(*SHAPES[4])

    def test_label_frameless(self) -> None:
        self._render_and_compare(*SHAPES[5])


if __name__ == "__main__":
    unittest.main()
