# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_lids_base_render.py
#    Renders a representative sample of lids_base.py shapes with the *real* PythonSCAD binary
#    and compares them against committed golden images. Complements tests/test_lids_base.py
#    (pure-Python dense-shape-type helpers only). Every one of the shapes below turned up a real
#    bug the first time it was actually rendered (see git history for specifics). LidMeshBasic
#    below is the predecessor of today's Lid + patterns.py path; the bugs are kept because they
#    are what these renders exist to catch, not because the class still exists:
#      - Bosl2Solid (pybosl2/ port) mixed directly into a native hull()/boolean without unwrapping
#        `.shape` first (make_lid_tab's wedge hull())
#      - color(obj, colorspec) argument order backwards (LidMeshBasic's border/bound)
#      - offset() (a 2-D op) called *after* linear_extrude() instead of before, silently
#        producing empty geometry (LidMeshBasic's border/bound)
#      - calc_path built BOSL2-anchor-style (centered on the origin) instead of matching classic
#        square()'s corner-anchored convention, leaving half the mesh's tiling area unaligned
#        with (and outside) the boundary it's supposed to fill (LidMeshBasic)
#    None of these are catchable by a numeric mock -- they only show up once real geometry is
#    actually meshed and composed.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available: no PythonSCAD binary, or no working BOSL2/std.scad for PythonSCAD
#    (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ (shared with the other render-test modules) and
#    are generated by tests/generate_golden_images.py (run manually on a machine where rendering
#    works; it dispatches to every module's SHAPES list).
#
# FileGroup: lids_base

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
# mock_libfive.py/render_pysolidfive.py now live inside pysolidfive/tests/ (moved there so
# pysolidfive's own test suite is bundled with the package); add that directory too.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_cap_box import find_bosl2_scad_dir
from render_lids_base import render_lids_base_shape
from render_app import compare_images, find_pythonscad_binary

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

# (test-name-suffix, lids_base.py expression) -- one per distinct technique rather than one per
# public function:
#   - lidmesh_dense: Lid(shape_options=...) -> ShapePattern -> a dense hex honeycomb tiled
#     across the whole boundary
#   - lidmesh_repeating: Lid(children=...) -> TiledMotif -> GridLattice, tiling a raw motif
#     (with gaps, unlike a gapless square, so the pattern is visible). The motif here is a
#     NATIVE square() on purpose: `children` is typed PyOpenSCAD, and handing TiledMotif a
#     native handle used to die with "Unknown color representation".
#   - sliding_fingernail: sliding_lid_fingernail's cylinder + sphere/cube cutout
#   - tabs: make_tabs + make_lid_tab's hull()-based wedge geometry
#   - build_lid: the carve-and-stack composition helper. TWO overlays, because one overlay
#     only exercises the base-carving loop -- the second is what drives the nested loop that
#     carves overlay j out of overlay i. They are also deliberately tall enough to change the
#     picture: with a flat 20x10 overlay this render moves by 2.11 against a tolerance of 12,
#     i.e. the golden could not see the composition it is supposed to be testing.
#
# The first three used to name LidMeshBasic / internal_build_lid, which no longer exist. That
# did NOT fail the suite -- render_lids_base_shape turns an exception into result.ok=False and
# the helper below calls skipTest(), so three dead tests reported as "skipped" for as long as
# they were broken. Check skip reasons, not just the OK line.
SHAPES = [
    (
        "lidmesh_dense",
        "Lid(shape_options=MakeShapeObject(shape_type=ShapeType.DENSE_HEX, shape_thickness=2, "
        "shape_width=10), boundary=10.0, layout_width=10.0)"
        ".mesh(LidFit(width=100.0, length=50.0, thickness=2.0))",
    ),
    (
        "lidmesh_repeating",
        "Lid(children=square([6, 6], center=True), boundary=10.0, layout_width=10.0)"
        ".mesh(LidFit(width=100.0, length=50.0, thickness=2.0))",
    ),
    ("sliding_fingernail", "sliding_lid_fingernail(3.0)"),
    ("lid_tabs", "make_tabs([50.0, 100.0], children=make_lid_tab(length=10.0, height=6.0))"),
    (
        "build_lid",
        "build_lid(base=cube([50, 30, 2]), overlays=["
        "cube([44, 24, 8]).translate([3, 3, 0]).color('red'), "
        "cube([16, 10, 14]).translate([17, 10, 0]).color('blue')], lid_thickness=2.0)",
    ),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_lids_base_shape(expr, out_png)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )

    def test_lidmesh_dense(self) -> None:
        self._render_and_compare(*SHAPES[0])

    def test_lidmesh_repeating(self) -> None:
        self._render_and_compare(*SHAPES[1])

    def test_sliding_fingernail(self) -> None:
        self._render_and_compare(*SHAPES[2])

    def test_lid_tabs(self) -> None:
        self._render_and_compare(*SHAPES[3])

    def test_build_lid(self) -> None:
        self._render_and_compare(*SHAPES[4])


if __name__ == "__main__":
    unittest.main()
