# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_boxes_render.py
#    Renders a representative sample of the remaining box modules (sliding_catch_box.py,
#    hinge_box.py, magnetic_box.py, dividers.py, inset_box.py, filament_hinge_box.py,
#    card_library.py, cap_box_polygon.py) with the *real* PythonSCAD binary and compares
#    them against committed golden images -- the regression baseline for the pysolidfive
#    migration of those files (goldens captured from the pre-migration pybosl2
#    implementations; the migrated code must match within tolerance).
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ and are generated by
#    tests/generate_golden_images.py.
#
# FileGroup: boxes

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_cap_box import find_bosl2_scad_dir
from render_pysolidfive import compare_images, find_pythonscad_binary
from render_boxes import render_boxes_shape

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

# These boxes are bigger, more detailed assemblies than the primitive pysolidfive/components
# shapes -- rendered (and diffed against) at a higher resolution; same rationale as
# test_cap_box_render.py's IMGSIZE.
IMGSIZE = (640, 480)

# (test-name-suffix, box-module expression) -- one per distinct construction technique. Every
# box gets its base form plus whichever lid/hinge/label paths are separate code paths.
SHAPES = [
    # sliding_catch_box.py: the catch grooves are the box's own construction; the lid's
    # catch fingers and the composed label lid are each their own path.
    ("sliding_catch_box_basic", "MakeBoxWithSlidingCatchLid([100.0, 50.0, 20.0])"),
    ("sliding_catch_lid_basic", "SlidingCatchBoxLid([100.0, 50.0, 20.0])"),
    ("sliding_catch_lid_with_label", "SlidingCatchBoxLidWithLabel([100.0, 50.0, 20.0], text_str='Catch')"),
    # hinge_box.py: the print-in-place box+lid assembly, and the bare inset hinge (the
    # hinge-line cone/knuckle construction is the piece being migrated).
    ("hinge_box_basic", "MakeBoxAndLidWithInsetHinge([100.0, 50.0, 20.0])"),
    ("hinge_box_inset_hinge", "InsetHinge(length=40, width=13, diameter=6, offset=0.3)"),
    # magnetic_box.py: corner magnet holes in the box, the lid's matching posts, and the
    # composed label lid.
    ("magnetic_box_basic", "MakeBoxWithMagneticLid([100.0, 50.0, 20.0], magnet_diameter=5, magnet_thickness=2)"),
    ("magnetic_lid_basic", "MagneticBoxLid([100.0, 50.0, 20.0], magnet_diameter=5, magnet_thickness=2)"),
    (
        "magnetic_lid_with_label",
        "MagneticBoxLidWithLabel([100.0, 50.0, 20.0], magnet_diameter=5, magnet_thickness=2, text_str='Magnet')",
    ),
    # dividers.py: the tabbed divider plate, and the text-in-tab variant.
    ("divider_basic", "MakeDivider(size=[40.0, 70.0, 1.0], tab_height=10, num_tabs=3, tab_position=0)"),
    (
        "divider_with_text",
        "MakeDividerWithText(size=[40.0, 70.0, 1.0], tab_height=10, text_str='Div', num_tabs=3, tab_position=1)",
    ),
    # inset_box.py: the tabbed box+lid pair, and the rabbit-clip pair (the clip is the
    # separate construction being migrated).
    ("inset_box_tabbed", "MakeBoxWithInsetLidTabbed([100.0, 50.0, 20.0])"),
    ("inset_lid_tabbed", "InsetLidTabbed([100.0, 50.0, 20.0])"),
    ("inset_box_rabbit", "MakeBoxWithInsetLidRabbitClip([100.0, 50.0, 20.0])"),
    ("inset_lid_rabbit", "InsetLidRabbitClip([100.0, 50.0, 20.0])"),
    ("inset_lid_rabbit_label", "InsetLidRabbitClipWithLabel([100.0, 50.0, 20.0], text_str='Rabbit')"),
    # filament_hinge_box.py: the box (knuckle hinges on the back edge), its lid, and the
    # composed label lid.
    (
        "filament_hinge_box_basic",
        "MakeBoxWithFilamentHingeLid([100.0, 50.0, 20.0])",
    ),
    (
        "filament_hinge_lid_basic",
        "MakeLidForFilamentBox([100.0, 50.0, 20.0])",
    ),
    (
        "filament_hinge_lid_label",
        "FilamentHingeBoxLidWithLabel([100.0, 50.0, 20.0], text_str='Hinge')",
    ),
    # card_library.py: the hinged library box in its two latch styles, the lid, the composed
    # label lid, and the card sleeve (its own offset_sweep construction).
    ("card_library_box_sliding", "MakeCardLibraryBox([100.0, 50.0, 40.0])"),
    ("card_library_box_clip", "MakeCardLibraryBox([100.0, 50.0, 40.0], latch=CARD_LIBRARY_LATCH_CLIP)"),
    ("card_library_lid", "CardLibraryBoxLid([100.0, 50.0, 40.0])"),
    ("card_library_lid_label", "CardLibraryBoxLidWithLabel([100.0, 50.0, 40.0], label='Cards')"),
    (
        "card_library_sleeve",
        "CardSleeveForLibrary(20, MakeCardSize(88, 63, 0.5), label='Deck')",
    ),
    # cap_box_polygon.py: a pentagon-outline cap box (finger holes + catches along the
    # segments), its cap lid, and the composed label lid.
    (
        "cap_polygon_box",
        "MakePathBoxWithCapLid(path=[[0, 0], [0, 60], [45, 90], [90, 60], [90, 0]], height=25, lid_catch=CatchType.ALL)",
    ),
    (
        "cap_polygon_lid",
        "CapPathBoxLid(path=[[0, 0], [0, 60], [45, 90], [90, 60], [90, 0]], height=25, lid_catch=CatchType.ALL)",
    ),
    (
        "cap_polygon_lid_label",
        "CapPathBoxLidWithLabel(path=[[0, 0], [0, 60], [45, 90], [90, 60], [90, 0]], height=25, text_str='Poly')",
    ),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_boxes_shape(expr, out_png, imgsize=IMGSIZE)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )


def _make_test(name: str, expr: str):
    def test(self: RealRenderTestCase) -> None:
        self._render_and_compare(name, expr)

    test.__name__ = f"test_{name}"
    return test


for _name, _expr in SHAPES:
    setattr(RealRenderTestCase, f"test_{_name}", _make_test(_name, _expr))


if __name__ == "__main__":
    unittest.main()
