# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_base_bgtk_render.py
#    Renders base_bgtk.py's only actual geometry-producing functions -- DifferenceWithOffset()/
#    DifferenceWithOffsetRounded()'s CSG-object ("children=") form -- with the *real* PythonSCAD
#    binary and compares them against committed golden images. Complements
#    tests/test_base_bgtk.py (Vec3/ResolveChild/enums/dataclasses only). The "pts=" (raw 2-D
#    region) form isn't rendered here: it returns region data (a list of point-list paths, one
#    of which is the "hole"), not a solid, so a caller has to flatten it into native polygon()'s
#    points/paths form to view it at all -- confirmed correct by hand, but not worth the extra
#    test-only plumbing when the children= form already exercises the same offset/difference
#    logic and produces a directly renderable 2-D solid.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available: no PythonSCAD binary, or no working BOSL2/std.scad for PythonSCAD
#    (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ (shared with the other render-test modules) and
#    are generated by tests/generate_golden_images.py (run manually on a machine where rendering
#    works; it dispatches to every module's SHAPES list).
#
# FileGroup: base_bgtk

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
# mock_libfive.py/render_pysolidfive.py now live inside pysolidfive/tests/ (moved there so
# pysolidfive's own test suite is bundled with the package); add that directory too.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_base_bgtk import render_base_bgtk_shape
from render_cap_box import find_bosl2_scad_dir
from render_pysolidfive import compare_images, find_pythonscad_binary

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

# (test-name-suffix, base_bgtk.py expression) -- one per distinct code path: an outline cutout
# (offset != 0), a solid pass-through (offset == 0, no cutout), and the rounded-corner variant.
SHAPES = [
    (
        "diff_offset_outline",
        "DifferenceWithOffset(offset=-3, children=square([30, 30], center=True)).linear_extrude(height=2)",
    ),
    (
        "diff_offset_solid",
        "DifferenceWithOffset(offset=0, outer_offset=-2, children=square([30, 30], center=True)).linear_extrude(height=2)",
    ),
    (
        "diff_offset_rounded_outline",
        "DifferenceWithOffsetRounded(offset=-3, children=square([30, 30], center=True)).linear_extrude(height=2)",
    ),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_base_bgtk_shape(expr, out_png)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )

    def test_diff_offset_outline(self) -> None:
        self._render_and_compare(*SHAPES[0])

    def test_diff_offset_solid(self) -> None:
        self._render_and_compare(*SHAPES[1])

    def test_diff_offset_rounded_outline(self) -> None:
        self._render_and_compare(*SHAPES[2])


if __name__ == "__main__":
    unittest.main()
