# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_cap_box_render.py
#    Renders a representative sample of cap_box.py shapes with the *real* PythonSCAD binary
#    (real BOSL2, real Manifold/CGAL booleans) and compares them against committed golden
#    images. cap_box.py is plain CSG (cuboid/wedge/sphere unions, differences, roundovers) via
#    the bosl2/ pure-Python port plus a couple of real-BOSL2 calls (reorient(), offset()) --
#    unlike pysolidfive's SDF/frep() path, so this exercises a different failure mode: real
#    boolean-CSG correctness (a wrong translate/rotate before a union, a mismatched anchor, a
#    stray NameError from an incomplete .scad->.py port) rather than SDF meshing edge cases.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available: no PythonSCAD binary (see pysolidfive/tests/render_pysolidfive.py), or no working
#    BOSL2/std.scad for PythonSCAD (see tests/render_cap_box.py's module docstring -- the
#    version_num() check in the real ~/Documents/OpenSCAD/libraries/BOSL2 install rejects
#    PythonSCAD's own version scheme, so a locally-patched copy is needed; BOSL2_SCAD_DIR
#    points at it).
#
#    Golden images live in tests/golden_images/ (pysolidfive's own golden images live separately,
#    in pysolidfive/tests/golden_images/) and are generated by tests/generate_golden_images.py
#    (run manually on a machine where rendering works; it dispatches to both pysolidfive's and
#    cap_box's SHAPES lists).
#
# FileGroup: cap_box

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
# mock_libfive.py/render_pysolidfive.py now live inside pysolidfive/tests/ (moved there so
# pysolidfive's own test suite is bundled with the package); add that directory too.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_cap_box import find_bosl2_scad_dir, render_cap_box_shape
from render_pysolidfive import compare_images, find_pythonscad_binary

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE: loose enough for anti-aliasing/
# viewport differences across machines, tight enough to catch a genuinely wrong shape or a
# blank/error image.
_TOLERANCE = 12.0

# These boxes/lids are larger, more detailed assemblies than the primitive pysolidfive/components
# shapes (rounded corners, finger holes, lid catches all in one image), so the default 320x240
# doesn't leave enough pixels to tell a subtly-wrong catch/rounding apart from anti-aliasing
# noise -- render (and diff against) these at a higher resolution instead.
IMGSIZE = (640, 480)

# (test-name-suffix, cap_box expression) -- one per distinct code path rather than one per public
# function: a plain box+lid (the common case), a box with a carved interior compartment (the
# children= carving path), and an explicit ALL lid_catch (the wedge-catch geometry path, as
# opposed to the default BUMPS_* nub catches the plain box/lid cases already exercise).
SHAPES = [
    ("cap_box_basic", "MakeBoxWithCapLid([80.0, 60.0, 20.0])"),
    (
        "cap_box_compartment",
        "MakeBoxWithCapLid([80.0, 60.0, 20.0], children=lambda inner: ["
        "InnerObject(value=cube([30, 20, 10]).translate([5, 5, 0]), type=ObjectType.NEGATIVE)])",
    ),
    ("cap_box_lid_basic", "CapBoxLid([80.0, 60.0, 20.0])"),
    ("cap_box_lid_wedge_catch", "CapBoxLid([80.0, 60.0, 20.0], lid_catch=CatchType.ALL)"),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_cap_box_shape(expr, out_png, imgsize=IMGSIZE)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )

    def test_cap_box_basic(self) -> None:
        self._render_and_compare(*SHAPES[0])

    def test_cap_box_compartment(self) -> None:
        self._render_and_compare(*SHAPES[1])

    def test_cap_box_lid_basic(self) -> None:
        self._render_and_compare(*SHAPES[2])

    def test_cap_box_lid_wedge_catch(self) -> None:
        self._render_and_compare(*SHAPES[3])


if __name__ == "__main__":
    unittest.main()
