# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_flags_render.py
#    Renders every public flags.py function with the real PythonSCAD binary and compares
#    against committed golden images.
#
#    flags.py had NO render coverage at all, which mattered because it is the module most in
#    need of change: ~800 of its 1464 lines are hand-traced bezier coordinate literals
#    (MiddleScrollsBlack alone is 581), and the plan is to replace those with SVG assets.
#    Rewriting 800 lines of coordinates with nothing to compare against is exactly how the
#    silent-geometry bugs in this codebase have happened -- an outline can come out subtracted
#    instead of added, or mirrored, and still render "successfully". These goldens are the
#    safety net that conversion needs.
#
#    Every test skips gracefully -- via self.skipTest(), not a failure -- when the real render
#    isn't available: no PythonSCAD binary, or no working BOSL2/std.scad.
#
#    Golden images live in tests/golden_images/ and are generated by
#    tests/generate_golden_images.py.
#
# FileSummary: Real-render tests for flags.py against golden images.
# FileGroup: Tests

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from render_app import compare_images, find_pythonscad_binary
from render_cap_box import find_bosl2_scad_dir
from render_flags import render_flag

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"
IMGSIZE = (320, 240)

# Same rationale/value as the other render suites' tolerance.
_TOLERANCE = 12.0

# One case per public flag, plus the two shared building blocks the crosses are made from.
# Sizes are picked to keep every flag's proportions close to the real thing, since the point
# is to notice a shape changing rather than to print these.
FLAGS = [
    ("flag_st_andrews_cross", "StAndrewsCross(60, 40)"),
    ("flag_st_patricks_cross", "StPatricksCross(60, 40)"),
    ("flag_st_georges_cross", "StGeorgesCross(60, 40, 30)"),
    ("flag_union_jack", "UnionJack(60, 40, 30)"),
    ("flag_australian", "AustralianFlag(60, 40, 30, 20)"),
    ("flag_sweden", "SwedenFlag(60, 40)"),
    ("flag_united_states", "UnitedStatesFlag(60, 40, 30, 20)"),
    ("flag_portugese", "PortugeseFlag(60, 40)"),
    # The background/border wrapper every flag composes onto. It requires children[0]
    # (the cutout) and children[1] (the face), so it is exercised with a simple pair.
    (
        "flag_background_border",
        "FlagBackgroundAndBorder(60, 40, 'blue', border=2, children=["
        "shapes3d.cuboid([30, 20, 10], anchor=BOTTOM), "
        "shapes3d.cuboid([30, 20, 2], anchor=BOTTOM)])",
    ),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_flag(expr, out_png, imgsize=IMGSIZE)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )


def _make_test(name: str, expr: str):
    def test(self: RealRenderTestCase) -> None:
        self._render_and_compare(name, expr)

    test.__name__ = f"test_{name}"
    return test


for _name, _expr in FLAGS:
    setattr(RealRenderTestCase, f"test_{_name}", _make_test(_name, _expr))


if __name__ == "__main__":
    unittest.main()
