# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_shapes_render.py
#    Renders EVERY 2-D lid-pattern shape in shapes.py (extruded, so the camera has a solid to
#    frame) with the *real* PythonSCAD binary and compares them against committed golden
#    images. The goldens were generated from the original native/pybosl2 implementation, so they
#    double as the regression baseline for the pysolidfive migration. Only the non-geometry
#    helpers (MakeShapeObject(), the *Width() calculators) are left to tests/test_shapes.py's
#    mock tests.
#
#    One test method per SHAPES entry, generated dynamically at import time -- with 37 shapes,
#    hand-written one-liner methods would just be noise.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ and are generated by
#    tests/generate_golden_images.py.
#
# FileGroup: shapes

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_cap_box import find_bosl2_scad_dir
from render_pysolidfive import compare_images, find_pythonscad_binary
from render_shapes import render_shapes_shape

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

# Fine 2-D detail (thin outlines, stroke paths) -- rendered (and diffed against) at a higher
# resolution, same rationale as test_labels_render.py's IMGSIZE.
IMGSIZE = (640, 480)

# Every public geometry-producing function in shapes.py, each extruded 2mm for rendering.
_E = ".linear_extrude(height=2)"
SHAPES = [
    ("shape_sword", f"Sword2d(70, 20){_E}"),
    ("shape_sword_outline", f"Sword2dOutline(70, 20, line_width=1.5){_E}"),
    ("shape_crossbow", f"Crossbow2d(50, 40){_E}"),
    ("shape_crossbow_outline", f"Crossbow2dOutline(50, 40, line_width=1.5){_E}"),
    ("shape_sledgehammer", f"Sledgehammer2d(50, 25){_E}"),
    ("shape_sledgehammer_outline", f"Sledgehammer2dOutline(50, 25, line_width=1.5){_E}"),
    ("shape_shoe", f"Shoe2d(40){_E}"),
    ("shape_shoe_outline", f"Shoe2dOutline(40, line_width=1.5){_E}"),
    ("shape_bag", f"Bag2d(40){_E}"),
    ("shape_bag_outline", f"Bag2dOutline(40, line_width=1.5){_E}"),
    ("shape_torch", f"Torch2d(50, 20){_E}"),
    ("shape_torch_outline", f"Torch2dOutline(50, 20, line_width=1.5){_E}"),
    ("shape_teapot", f"Teapot2d(40, 30){_E}"),
    ("shape_coin_text", f"Coin2d(30, text='5'){_E}"),
    ("shape_coin_pile", f"CoinPile2d(40){_E}"),
    ("shape_australia", f"AustraliaMap2d(50){_E}"),
    ("shape_rock", f"Rock2d(40, 30){_E}"),
    ("shape_ruins", f"Ruins2d(40){_E}"),
    ("shape_rock_wall", f"RockWall2d(40){_E}"),
    ("shape_d20_outline", f"D20Outline2d(40, offset=2){_E}"),
    ("shape_sawblade", f"SawBlade2d(40){_E}"),
    ("shape_sawblade_outline", f"SawBlade2dOutline(40){_E}"),
    ("shape_handshake", f"Handshake2d(40){_E}"),
    ("shape_fist", f"Fist2d(40){_E}"),
    ("shape_fist_outline", f"Fist2dOutline(40, line_width=1.5){_E}"),
    ("shape_leaf", f"Leaf2d(40){_E}"),
    ("shape_laurel_wreath", f"LaurelWreath2d(40){_E}"),
    ("shape_anvil", f"Anvil2d(40){_E}"),
    ("shape_anvil_hammer", f"Anvil2d(40, with_hammer=True){_E}"),
    ("shape_half_eye", f"HalfEye2d(45){_E}"),
    ("shape_side_eye", f"SideEye2d(45){_E}"),
    ("shape_cloud", f"CloudShape2d(40){_E}"),
    ("shape_single_log", f"SingleLog2d(40){_E}"),
    ("shape_tower", f"Tower2d(40){_E}"),
    ("shape_sign", f"Sign2d(40){_E}"),
    ("shape_portugal_castle", f"PortugalCastle(stroke_width=1.5, width=40){_E}"),
    ("shape_train_outline", f"TrainOutline(60){_E}"),
    ("shape_wagon_outline", f"WagonOutline(60){_E}"),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_shapes_shape(expr, out_png, imgsize=IMGSIZE)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )


def _make_test(name: str, expr: str):
    def test(self: RealRenderTestCase) -> None:
        self._render_and_compare(name, expr)

    test.__name__ = f"test_{name}"
    return test


for _name, _expr in SHAPES:
    setattr(RealRenderTestCase, f"test_{_name}", _make_test(_name, _expr))


if __name__ == "__main__":
    unittest.main()
