# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_sliding_box_render.py
#    Renders a representative sample of sliding_box.py shapes with the *real* PythonSCAD binary
#    and compares them against committed golden images. Complements tests/test_sliding_box.py
#    (MakeSlidingLidOptions() only). Every one of the shapes below turned up a real bug the
#    first time it was actually rendered (see git history for specifics):
#      - bare cuboid(...) instead of shapes3d.cuboid(...) (a leftover, un-prefixed name from
#        the .scad->.py port -- the same NameError class of bug already fixed once in
#        cap_box.py/labels.py, but present in three more call sites here)
#      - a bare BOSL2 module call, mask2d_roundover(...), used the way real BOSL2 dispatches it
#        as a *module* (producing geometry directly inside linear_extrude()) -- the pybosl2/ port
#        only implements its *function* form (returning raw path data), so it needs an explicit
#        polygon(...) wrapper before extruding
#      - lids_base.py's internal_build_lid() calling .fill() as a method -- fill() only exists
#        as a free function, fill(obj), not a bound method
#      - Bosl2Solid (pybosl2/ port) mixed directly into a native boolean op without unwrapping
#        `.shape` first, and labels.py's label functions leaking a Bosl2Solid return value
#        instead of the native type every sibling function returns -- both break
#        internal_build_lid()'s union of a lid's several children as soon as one of them
#        happens to be a different type than its neighbours
#    None of these are catchable by a numeric mock -- they only show up once real geometry is
#    actually meshed and composed.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available: no PythonSCAD binary, or no working BOSL2/std.scad for PythonSCAD
#    (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ (shared with the other render-test modules) and
#    are generated by tests/generate_golden_images.py (run manually on a machine where rendering
#    works; it dispatches to every module's SHAPES list).
#
# FileGroup: sliding_box

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
# render_pysolidfive.py lives inside the installed pysolidfive package in the venv.
_venv_pysolidfive_tests = (
    Path(__file__).resolve().parent.parent / ".venv" / "lib"
    / f"python{sys.version_info.major}.{sys.version_info.minor}"
    / "site-packages" / "pysolidfive" / "tests"
)
if _venv_pysolidfive_tests.is_dir():
    sys.path.insert(0, str(_venv_pysolidfive_tests))

from render_cap_box import find_bosl2_scad_dir
from render_pysolidfive import compare_images, find_pythonscad_binary
from render_sliding_box import render_sliding_box_shape

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

# These lids/boxes are bigger, more detailed assemblies than the primitive pysolidfive/components
# shapes (and the label/pattern variants have fine surface detail too) -- rendered (and diffed
# against) at a higher resolution; same rationale as test_cap_box_render.py's IMGSIZE.
IMGSIZE = (640, 480)

# (test-name-suffix, sliding_box.py expression) -- one per distinct technique rather than one
# per public function: a plain single-layer lid, the two-layer lid variant (a different code
# path through SlidingLid() entirely), the matching box cutouts for both, the lid with a
# repeating pattern mesh, and the fully composed lid+label+pattern+finger-holes (the most
# integrated case, exercising internal_build_lid()'s multi-child union).
SHAPES = [
    ("sliding_lid_basic", "SlidingLid([80.0, 60.0])"),
    (
        "sliding_lid_two_layer",
        "SlidingLid([80.0, 60.0], sliding_lid_options=MakeSlidingLidOptions(two_layer=True))",
    ),
    ("box_with_sliding_lid_basic", "MakeBoxWithSlidingLid([80.0, 60.0, 20.0])"),
    (
        "box_with_sliding_lid_two_layer",
        "MakeBoxWithSlidingLid([80.0, 60.0, 20.0], sliding_lid_options=MakeSlidingLidOptions(two_layer=True))",
    ),
    ("sliding_lid_with_shape", "SlidingBoxLidWithShape([80.0, 60.0])"),
    ("sliding_lid_with_label", "SlidingBoxLidWithLabel([80.0, 60.0], text_str='Frog')"),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_sliding_box_shape(expr, out_png, imgsize=IMGSIZE)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )

    def test_sliding_lid_basic(self) -> None:
        self._render_and_compare(*SHAPES[0])

    def test_sliding_lid_two_layer(self) -> None:
        self._render_and_compare(*SHAPES[1])

    def test_box_with_sliding_lid_basic(self) -> None:
        self._render_and_compare(*SHAPES[2])

    def test_box_with_sliding_lid_two_layer(self) -> None:
        self._render_and_compare(*SHAPES[3])

    def test_sliding_lid_with_shape(self) -> None:
        self._render_and_compare(*SHAPES[4])

    def test_sliding_lid_with_label(self) -> None:
        self._render_and_compare(*SHAPES[5])


if __name__ == "__main__":
    unittest.main()
