# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_no_lid_render.py
#    Renders a representative sample of no_lid.py shapes with the *real* PythonSCAD binary and
#    compares them against committed golden images. Complements tests/test_no_lid.py (plain-
#    Python pieces only). The golden images were generated from the original pybosl2/offset_sweep-
#    based implementation, so they double as the regression baseline for the pysolidfive
#    migration of no_lid.py's solids.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available: no PythonSCAD binary, or no working BOSL2/std.scad for PythonSCAD
#    (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ (shared with the other render-test modules) and
#    are generated by tests/generate_golden_images.py (run manually on a machine where rendering
#    works; it dispatches to every module's SHAPES list).
#
# FileGroup: no_lid

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
# mock_libfive.py/render_pysolidfive.py now live inside pysolidfive/tests/ (moved there so
# pysolidfive's own test suite is bundled with the package); add that directory too.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_cap_box import find_bosl2_scad_dir
from render_no_lid import render_no_lid_shape
from render_pysolidfive import compare_images, find_pythonscad_binary

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

# These boxes are bigger, more detailed assemblies than the primitive pysolidfive/components
# shapes -- rendered (and diffed against) at a higher resolution; same rationale as
# test_cap_box_render.py's IMGSIZE.
IMGSIZE = (640, 480)

# (test-name-suffix, no_lid.py expression) -- one per distinct technique rather than one per
# public function: the plain cuboid box and its hollow variant (MakeBoxWithNoLid's own code
# path), the path box in plain/hollow/both-stackable variants plus a concave path (the
# offset_sweep-based engine all the path/polygon boxes go through, including the interior
# stackable-ring construction), and the polygon box (regular-hexagon delegation into the path
# engine, plus the finger-hole placement along non-axis-aligned edges).
SHAPES = [
    ("box_no_lid_basic", "MakeBoxWithNoLid([80.0, 60.0, 20.0])"),
    ("box_no_lid_hollow", "MakeBoxWithNoLid([80.0, 60.0, 20.0], hollow=True)"),
    (
        "path_box_no_lid_basic",
        "MakePathBoxWithNoLid(path=[[0, 0], [80, 0], [80, 60], [0, 60]], height=20.0)",
    ),
    (
        "path_box_no_lid_hollow",
        "MakePathBoxWithNoLid(path=[[0, 0], [80, 0], [80, 60], [0, 60]], height=20.0, hollow=True)",
    ),
    (
        "path_box_no_lid_concave",
        "MakePathBoxWithNoLid(path=[[0, 0], [80, 0], [80, 30], [40, 30], [40, 60], [0, 60]], height=20.0, hollow=True)",
    ),
    (
        "path_box_no_lid_stackable_inside",
        "MakePathBoxWithNoLid(path=[[0, 0], [80, 0], [80, 60], [0, 60]], height=20.0, hollow=True, "
        "stackable=STACKABLE_TYPE_INSIDE)",
    ),
    (
        "path_box_no_lid_stackable_outside",
        "MakePathBoxWithNoLid(path=[[0, 0], [80, 0], [80, 60], [0, 60]], height=20.0, hollow=True, "
        "stackable=STACKABLE_TYPE_OUTSIDE)",
    ),
    ("polygon_box_no_lid_hex", "MakePolygonBoxWithNoLid([80.0, 20.0], sides=6)"),
    ("polygon_box_no_lid_hex_hollow", "MakePolygonBoxWithNoLid([80.0, 20.0], sides=6, hollow=True)"),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_no_lid_shape(expr, out_png, imgsize=IMGSIZE)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )

    def test_box_no_lid_basic(self) -> None:
        self._render_and_compare(*SHAPES[0])

    def test_box_no_lid_hollow(self) -> None:
        self._render_and_compare(*SHAPES[1])

    def test_path_box_no_lid_basic(self) -> None:
        self._render_and_compare(*SHAPES[2])

    def test_path_box_no_lid_hollow(self) -> None:
        self._render_and_compare(*SHAPES[3])

    def test_path_box_no_lid_concave(self) -> None:
        self._render_and_compare(*SHAPES[4])

    def test_path_box_no_lid_stackable_inside(self) -> None:
        self._render_and_compare(*SHAPES[5])

    def test_path_box_no_lid_stackable_outside(self) -> None:
        self._render_and_compare(*SHAPES[6])

    def test_polygon_box_no_lid_hex(self) -> None:
        self._render_and_compare(*SHAPES[7])

    def test_polygon_box_no_lid_hex_hollow(self) -> None:
        self._render_and_compare(*SHAPES[8])


if __name__ == "__main__":
    unittest.main()
