# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_components_render.py
#    Renders a representative sample of components.py shapes with the *real* PythonSCAD binary
#    and compares them against committed golden images. Complements tests/test_components.py
#    (pure-Python math helpers only). components.py mixes three different shape-building
#    styles -- native primitives, the pybosl2/ pure-Python port (returns Bosl2Solid, not a real
#    PyOpenSCAD -- mixing the two in a boolean op without unwrapping `.shape` crashes), and real
#    BOSL2 via osuse() (whose region functions, e.g. union()/difference()/offset_sweep(), return
#    plain point-list data when called as an expression, not geometry -- needs vnf_polyhedron()
#    to become a solid) -- so this is exactly the kind of real-CSG-boundary bug a numeric mock
#    can't catch: every one of the shapes below turned up a genuine crash or wrong-geometry bug
#    the first time it was actually rendered (see git history for specifics).
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available: no PythonSCAD binary, or no working BOSL2/std.scad for PythonSCAD
#    (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ (shared with the pysolidfive/cap_box render tests) and
#    are generated by tests/generate_golden_images.py (run manually on a machine where rendering
#    works; it dispatches to pysolidfive's, cap_box's, and components' SHAPES lists).
#
# FileGroup: components

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
# mock_libfive.py/render_pysolidfive.py now live inside pysolidfive/tests/ (moved there so
# pysolidfive's own test suite is bundled with the package); add that directory too.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_cap_box import find_bosl2_scad_dir
from render_components import render_components_shape
from render_pysolidfive import compare_images, find_pythonscad_binary

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

# (test-name-suffix, components.py expression) -- one per distinct shape-building technique
# rather than one per public function:
#   - rounded_box_on_length: hull() of two native xcyl()s (Bosl2Solid unwrapped via `.shape`)
#   - rounded_box_all_sides: hull() of native sphere()s only (no pybosl2/ port involved)
#   - regular_polygon: 2-D polygon linear_extrude() + Bosl2Solid finger-hole union
#   - cuboid_with_indents: pybosl2/ cuboid() with per-corner finger bumps
#   - magnet_slot_round: real BOSL2 reorient() (osuse()) + multmatrix()
#   - finger_hole_base: real BOSL2 rect()/offset_sweep() region pipeline -> vnf_polyhedron()
#   - finger_hole_wall: real BOSL2 square()/circle()/union()/difference() region-boolean
#     pipeline (the trickiest one -- these must be the real _bosl2.square()/circle(), not
#     shapes2d.py's, to get region/path data rather than solid geometry)
SHAPES = [
    ("rounded_box_on_length", "RoundedBoxOnLength([30.0, 20.0, 10.0], 7)"),
    ("rounded_box_all_sides", "RoundedBoxAllSides([30.0, 30.0, 10.0], 5)"),
    ("regular_polygon", "RegularPolygon(20.0, 8.0, shape_edges=6, finger_holes=[0, 3])"),
    (
        "cuboid_with_indents",
        "CuboidWithIndentsBottom([15.0, 10.0, 10.0], finger_holes=[1, 5], finger_hole_radius=3.0)",
    ),
    ("magnet_slot_round", "MagnetSlot(size=[10.0, 10.0, 2.0], magnet_type=MAGNET_SLOT_TYPE_ROUND)"),
    ("finger_hole_base", "FingerHoleBase(10.0, 20.0)"),
    ("finger_hole_wall", "FingerHoleWall(10.0, 20.0)"),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_components_shape(expr, out_png)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )

    def test_rounded_box_on_length(self) -> None:
        self._render_and_compare(*SHAPES[0])

    def test_rounded_box_all_sides(self) -> None:
        self._render_and_compare(*SHAPES[1])

    def test_regular_polygon(self) -> None:
        self._render_and_compare(*SHAPES[2])

    def test_cuboid_with_indents(self) -> None:
        self._render_and_compare(*SHAPES[3])

    def test_magnet_slot_round(self) -> None:
        self._render_and_compare(*SHAPES[4])

    def test_finger_hole_base(self) -> None:
        self._render_and_compare(*SHAPES[5])

    def test_finger_hole_wall(self) -> None:
        self._render_and_compare(*SHAPES[6])


if __name__ == "__main__":
    unittest.main()
