# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: tests/test_shapes3d_render.py
#    Renders every polyhedron in shapes3d.py with the *real* PythonSCAD binary and compares
#    them against committed golden images. The goldens were generated from the original
#    BOSL2-polyhedra/CSG implementation, so they double as the regression baseline for the
#    pysolidfive migration.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available (see tests/render_cap_box.py's module docstring).
#
#    Golden images live in tests/golden_images/ and are generated by
#    tests/generate_golden_images.py.
#
# FileGroup: shapes3d

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pysolidfive" / "tests"))

from render_cap_box import find_bosl2_scad_dir
from render_app import compare_images, find_pythonscad_binary
from render_shapes import render_shapes_shape

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Same rationale/value as pysolidfive/tests/test_pysolidfive_render.py's _TOLERANCE.
_TOLERANCE = 12.0

IMGSIZE = (320, 240)

SHAPES = [
    ("polyhedron_dodecahedron", "dodecahedron(20)"),
    ("polyhedron_tetrahedron", "tetrahedron(20)"),
    ("polyhedron_octahedron", "octahedron(20)"),
    ("polyhedron_icosahedron", "icosahedron(20)"),
    ("polyhedron_trapezohedron", "trapezohedron(20)"),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None
    bosl2_dir: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        cls.bosl2_dir = find_bosl2_scad_dir()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")
        if self.bosl2_dir is None:
            self.skipTest(
                "no working BOSL2/std.scad found for PythonSCAD (set BOSL2_SCAD_DIR; see "
                "tests/render_cap_box.py's module docstring)"
            )

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_shapes_shape(expr, out_png, imgsize=IMGSIZE)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )

    def test_polyhedron_dodecahedron(self) -> None:
        self._render_and_compare(*SHAPES[0])

    def test_polyhedron_tetrahedron(self) -> None:
        self._render_and_compare(*SHAPES[1])

    def test_polyhedron_octahedron(self) -> None:
        self._render_and_compare(*SHAPES[2])

    def test_polyhedron_icosahedron(self) -> None:
        self._render_and_compare(*SHAPES[3])

    def test_polyhedron_trapezohedron(self) -> None:
        self._render_and_compare(*SHAPES[4])


if __name__ == "__main__":
    unittest.main()
